In [15]:
import numpy as np
import pandas as pd

In [16]:
constituents_df = pd.read_excel('Constituent Data - Abbeywood University.xlsx', index_col='Alumni ID')

In [17]:
constituents_df.head()

,Full Name,Gender,Date of Birth,Age,Deceased,Nationality,Home City,Home Country,Phone Number,Email
Alumni ID,,,,,,,,,,
1,Thomas IvyTurner,Male,1941-03-06,85,NaN,British,Birmingham,United Kingdom,4.475469e+11,tivyturner@abbeywood.ac.uk
2,James WestJones,Male,1955-02-21,71,NaN,Spanish,Toronto,Canada,1.037056e+10,jwestjones@abbeywood.ac.uk
3,Charlotte IvyClark,Female,1967-02-02,59,NaN,British,Manchester,United Kingdom,4.472289e+11,civyclark@abbeywood.ac.uk
4,Georgia IvyTurner,Female,1949-06-12,77,NaN,British,London,United Kingdom,4.475057e+11,givyturner@abbeywood.ac.uk
5,Olivia GlenClark,Female,1945-04-06,81,NaN,British,Manchester,United Kingdom,NaN,oglenclark@abbeywood.ac.uk

In [18]:
constituents_df[ constituents_df['Deceased'].notna() ].count()

Full Name        884
Gender           884
Date of Birth    884
Age              884
Deceased         884
Nationality      884
Home City        884
Home Country     884
Phone Number     796
Email            872
dtype: int64

In [19]:
constituents_df.describe()

                    Date of Birth           Age  Phone Number
count                       10000  10000.000000  9.502000e+03
mean   1968-05-05 15:38:26.880000     58.147500  3.442489e+11
min           1931-01-02 00:00:00     21.000000  4.428780e+07
25%           1949-08-10 18:00:00     39.000000  9.662505e+10
50%           1967-12-30 00:00:00     58.500000  4.473258e+11
75%           1987-03-08 06:00:00     77.000000  4.476610e+11
max           2005-12-27 00:00:00     95.000000  4.479992e+11
std                           NaN     21.564889  1.762986e+11

In [20]:
constituents_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 1 to 10000
Data columns (total 10 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Full Name      10000 non-null  str
 1   Gender         10000 non-null  str
 2   Date of Birth  10000 non-null  datetime64[us]
 3   Age            10000 non-null  int64
 4   Deceased       884 non-null    str
 5   Nationality    10000 non-null  str
 6   Home City      10000 non-null  str
 7   Home Country   10000 non-null  str
 8   Phone Number   9502 non-null   float64
 9   Email          9595 non-null   str
dtypes: datetime64[us](1), float64(1), int64(1), str(7)
memory usage: 1.5 MB